- build.gradle
- src/main/resources/buildServerResources/buildScanCrumbSummary.jsp
- src/main/resources/buildServerResources/buildScanPage.jsp
Note that several instances of uppercase 'Build Scan(s)' still exist after this change:
```
$ git grep 'Build Scan'
README.md:[TeamCity](https://www.jetbrains.com/teamcity/) plugin that integrates with the Gradle Build Scan Service, the first service offered by [Gradle Cloud Services](https://gradle.com).
build.gradle:            displayName = 'Gradle Build Scan Integration'
src/main/java/nu/studer/teamcity/buildscan/BuildScanViewBuildTab.java:        super("Build Scan", "buildScan", pagePlaces, pluginDescriptor.getPluginResourcesPath("/buildScanPage.jsp"), buildServer);
```
These are places where any common noun would be capitalized, e.g. headings and titles, etc.
Note also that in the build scan crumb summary, "Build Scan:" has been changed to "Build scan:" in order to follow convention …
> Use lowercase 'build scan' where appropriate

- agent/service-message-maven-extension/src/main/java/nu/studer/teamcity/buildscan/agent/servicemessage/BuildScanServiceMessageMavenExtension.java
TeamCity applies its own Maven extensions with the same (i.e. `null`) hint. This causes a silent conflict and only one extension is resolved / applied - ours - causing the rest of the build pipeline completely lost resulting with unexpected behaviour. 
When we added a unique hint we printed out participants list 
```java
@Requirement
private List<AbstractMavenLifecycleParticipant> participantList;
```
we got this in the logs:
```
participantList = [com.jetbrains.maven.watcher.m3wrp.MavenLifecycleParticipant@7fcff1b9, nu.studer.teamcity.buildscan.agent.servicemessage.BuildScanServiceMessageMavenExtension@66eb985d]
```
which proves that we have more than one extension applied to the Maven build.
Adding a unique hint is equivalent of giving the "bean" a unique id / name.
Fixes #16
> Add unique hint to BuildScanServiceMessageMavenExtension

- build.gradle
This is an example of the configuration supported by the gradle-teamcity-plugin to publish a plugin to the
JetBrains plugin repository.
The section [Publishing a plugin](https://github.com/rodm/gradle-teamcity-plugin#publishing-a-plugin) describes that task and a link to setting up a [token](https://www.jetbrains.com/help/hub/Manage-Permanent-Tokens.html) with JetBrains.
The notes property can be plain text or HTML, I've experimented using the [changelog](https://plugins.gradle.org/plugin/org.jetbrains.changelog) plugin to create HTML from a changelog file in markdown format.
> Publish configuration

- .github/workflows/build-verification.yml
- .github/workflows/development-release.yml
- .github/workflows/production-release.yml
- README.md
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/main/resources/build-scan-init.gradle
This change adds configuration parameters to allow plugin users to
automatically apply and configure the Gradle Enterprise plugin from
TeamCity configuration parameters. `GRADLE_ENTERPRISE_URL` will set the
`gradleEnterprise.server` property. `GRADLE_ENTERPRISE_PLUGIN_VERSION`
will apply the specified version of the Gradle Enterprise plugin if not
already applied.
The change adds the `teamCityBuildScanPlugin.gradle.enterprise.url` and
`teamCityBuildScanPlugin.gradle.enterprise.plugin.version`
system properties to the injected init script in order to pass the
configuration parameters from TeamCity into Gradle.
Support for the CCUD Gradle plugin has been added, too.
> Add configurable auto-application of Gradle Enterprise plugin

- agent/service-message-maven-extension/src/main/java/nu/studer/teamcity/buildscan/agent/servicemessage/BuildScanServiceMessageMavenExtension.java
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/main/resources/build-scan-init.gradle
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/GradleEnterprisePluginApplicationTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/GradleEnterpriseExtensionApplicationTest.groovy
Provides a central mechanism for TC users to configure `allowUntrustedServer` for the configured GE URL, via a `buildScanPlugin.gradle-enterprise.allow-untrusted-server' configuration parameter. This parameter is supported for Gradle and Maven with both core and command-line runners.
- For Gradle the setting is applied in the init script
- For Maven the setting is mapped to a System Property supported by the TC Maven Extension
> Add TC config property to set allowUntrustedServer

- README.md
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/main/resources/build-scan-init.gradle
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/TestBuildScanServiceMessageInjector.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/TestContext.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/GradleEnterprisePluginApplicationTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/TcPluginConfig.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/GradleEnterpriseExtensionApplicationTest.groovy
- release/changes.md
- Refactored tests for Gradle jobs to use the `BuildScanServiceMessageInjector` to map TC Config params to Env Vars.
- Made the `build-scan-init` script safer to apply
- Script has no impact in the absence of Env Var with value matching script name
- When applying script directly via `--init-script`, then file name is 'build-scan-init.gradle'
- When script is added to Gradle User Home, it has a unique name: build-scan-init-<timestamp>.gradle
- Each intercepted job is run with the matching environment variable for the init-script
- Added test coverage for integration with CommandLine jobs
> Make the `build-scan-init` script safer to apply to Gradle User Home

- .github/workflows/build-verification.yml
- .github/workflows/development-release.yml
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/GradleEnterpriseExtensionApplicationTest.groovy
- Do not fail `build-verification` or `development-release` workflows if `GRADLE_ENTERPRISE_ACCESS_KEY` secret is unavailable. This allows workflows to pass for PRs submitted from forked repositories.
- Do not run `build-verification` and `development-release` workflows on the same triggers. This avoids duplicating the build effort on pushes to `master`.
> GitHub Actions improvements

- gradle/wrapper/gradle-wrapper.properties
Bumps Gradle Wrapper from 7.5 to 7.5.1.
Release notes of Gradle 7.5.1 can be found here:
https://docs.gradle.org/7.5.1/release-notes.html
> Bump Gradle Wrapper from 7.5 to 7.5.1

- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
Gradle TestKit does not set env-vars for older versions of Gradle on M1 mac.
In these scenarios use system properties instead.
> Workaround lack of env-var support on M1 mac

- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
The tests for "GE plugin already applied" were applying an old version of the GE plugin (3.4.1). This was not causing test failures, but resulted in `Build scan background action failed.` messages in the test log output.
Updating to use the latest GE plugin (3.11.1) removes these error messages.
> Update test to apply latest GE plugin version

- README.md
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/TcPluginConfig.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/GradleEnterpriseExtensionApplicationTest.groovy
- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionConstants.java
- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProvider.java
- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseParametersProvider.java
- src/main/resources/buildServerResources/geConnectionDialog.jsp
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseParametersProviderTest.groovy
Adds a `buildScanPlugin.maven-version-check.enabled` parameter that enables the Maven version check to prevent applying the Gradle Enterprise Maven Extension to Maven builds less than version 3.3.1. By default, this check is not enabled.
> Make the Maven version check configurable and disabled by default

- README.md
Links to compatibility documents for Gradle and shows what versions of Gradle Enterprise are compatible
with which TeamCity Build Scan plugin if auto-injection is enabled for Maven.
> Add Gradle Enterprise auto-injection compatibility

- gradle/wrapper/gradle-wrapper.properties
Bumps Gradle Wrapper from 7.6 to 7.6.
Release notes of Gradle 7.6 can be found here:
https://docs.gradle.org/7.6/release-notes.html
> Bump Gradle Wrapper from 7.6 to 7.6

- agent/service-message-maven-extension/src/main/java/nu/studer/teamcity/buildscan/agent/servicemessage/BuildScanServiceMessageMavenExtension.java
- agent/src/main/resources/build-scan-init.gradle
Since all builds instrumented by this plugin are CI builds, always set `UploadInBackground` for both Maven and Gradle builds.
Fixes https://github.com/etiennestuder/teamcity-build-scan-plugin/issues/166
> Disable Upload Scan in Background

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.8.6 to 3.8.7.
Release notes of Maven 3.8.7 can be found here:
https://maven.apache.org/docs/3.8.7/release-notes.html
> Bump Maven Wrapper from 3.8.6 to 3.8.7 in /agent/service-message-maven-extension

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.8.7 to 3.9.0.
Release notes of Maven 3.9.0 can be found here:
https://maven.apache.org/docs/3.9.0/release-notes.html
> Bump Maven Wrapper from 3.8.7 to 3.9.0 in /agent/service-message-maven-extension

- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/GradleEnterprisePluginApplicationTest.groovy
- settings.gradle
- src/main/resources/default-plugin-versions.properties
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
This PR updates the Gradle Enterprise Gradle plugin version from 3.12.3 to 3.12.4.
> Bump Gradle Enterprise Gradle Plugin version to 3.12.4

- README.md
- agent/build.gradle
- agent/service-message-maven-extension/.mvn/extensions.xml
- agent/service-message-maven-extension/pom.xml
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/GradleEnterpriseExtensionApplicationTest.groovy
- src/main/resources/default-plugin-versions.properties
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
This PR bumps the Gradle Enterprise Gradle plugin version from 1.16.4 to 1.16.5.
> Bump Gradle Enterprise Maven Extension version to 1.16.5

- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProvider.java
- src/main/java/nu/studer/teamcity/buildscan/internal/GradleEnterpriseAccessKeyValidator.java
- src/main/resources/META-INF/build-server-plugin-buildscans.xml
- src/main/resources/buildServerResources/geConnectionDialog.jsp
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
- src/test/groovy/nu/studer/teamcity/buildscan/internal/GradleEnterpriseAccessKeyValidatorTest.groovy
This PR improves the UX of the connection form by adding information about the expected format of the access key:
The access key is validated on the server and in case it is not valid the form is rejected with the error message:
> Validate Gradle Enterptise access token

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.9.0 to 3.9.1.
Release notes of Maven 3.9.1 can be found here:
https://maven.apache.org/docs/3.9.1/release-notes.html
> Bump Maven Wrapper from 3.9.0 to 3.9.1 in /agent/service-message-maven-extension

- README.md
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/main/resources/build-scan-init.gradle
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/TcPluginConfig.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/GEPluginApplicationInitScriptTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/UrlConfigurationExtensionApplicationTest.groovy
- release/changes.md
- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionConstants.java
- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProvider.java
- src/main/java/nu/studer/teamcity/buildscan/connection/GradleEnterpriseParametersProvider.java
- src/main/resources/buildServerResources/geConnectionDialog.jsp
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseParametersProviderTest.groovy
This PR adds a checkbox to the configuration UI to allow the GE URL configuration in the TeamCity Build Scan Plugin to override the values configured in projects. This may be useful for migrating projects from one server to another. In particular, it can be useful for projects that are already configured to upload scans to scans.gradle.com.
The behavior of this PR is that the values for GE URL and Allow Untrusted Server configured in the TeamCity Build Scan Plugin connection dialog will overwrite those found in the project when:
* GE version is configured
* The new override checkbox is enabled
> Gradle Enterprise server URL is overridable

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.9.1 to 3.9.2.
Release notes of Maven 3.9.2 can be found here:
https://maven.apache.org/docs/3.9.2/release-notes.html
> Bump Maven Wrapper from 3.9.1 to 3.9.2 in /agent/service-message-maven-extension

- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/GEPluginApplicationInitScriptTest.groovy
- settings.gradle
- src/main/resources/default-plugin-versions.properties
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
This PR bumps the default version of the Gradle Enterprise Gradle plugin version to 3.13.3.
> Use Gradle Enterprise Gradle plugin version 3.13.3 by default

- README.md
- agent/build.gradle
- agent/service-message-maven-extension/.mvn/extensions.xml
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/BaseExtensionApplicationTest.groovy
- src/main/resources/default-plugin-versions.properties
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
This PR bumps the Common Custom User Data Maven extension version from 1.11.1 to 1.12.
> Bump Common Custom User Data Maven extension version from 1.11.1 to 1.12

- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/BaseInitScriptTest.groovy
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/gradle/GEPluginApplicationInitScriptTest.groovy
- settings.gradle
- src/main/resources/default-plugin-versions.properties
- src/test/groovy/nu/studer/teamcity/buildscan/connection/GradleEnterpriseConnectionProviderTest.groovy
This PR upgrades the Common Custom User Data Gradle plugin version from 1.10 to 1.11.
> Bump Common Custom User Data Gradle plugin version from 1.10 to 1.11

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.9.2 to 3.9.3.
Release notes of Maven 3.9.3 can be found here:
https://maven.apache.org/docs/3.9.3/release-notes.html
> Bump Maven Wrapper from 3.9.2 to 3.9.3 in /agent/service-message-maven-extension

- agent/src/main/resources/build-scan-init.gradle
- release/changes.md
In order for the Gradle Enterprise plugin to deactivate any potentially build-changing features (at the time of writing that means all of its testing features) when applied via the init script rather than directly in the build, the `gradle.enterprise.externally-applied` system property is now set before applying it and reset afterwards.
> Set `gradle.enterprise.externally-applied` before applying GE plugin

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.9.3 to 3.9.4.
Release notes of Maven 3.9.4 can be found here:
https://maven.apache.org/docs/3.9.4/release-notes.html
> Bump Maven Wrapper from 3.9.3 to 3.9.4 in /agent/service-message-maven-extension

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.9.4 to 3.9.5.
Release notes of Maven 3.9.5 can be found here:
https://maven.apache.org/docs/3.9.5/release-notes.html
> Bump Maven Wrapper from 3.9.4 to 3.9.5 in /agent/service-message-maven-extension

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
Bumps Maven Wrapper from 3.9.5 to 3.9.6.
Release notes of Maven 3.9.6 can be found here:
https://maven.apache.org/docs/3.9.6/release-notes.html
> Bump Maven Wrapper from 3.9.5 to 3.9.6 in /agent/service-message-maven-extension

- agent/build.gradle
- agent/src/main/resources/build-scan-init.gradle
- agent/src/main/resources/init-scripts/build-scan-collector.groovy
- agent/src/main/resources/init-scripts/develocity-injection.init.gradle
- Add a copy of the latest reference init-script
- Leverage build-scan capture functionality with custom groovy script
- Compose final `build-scan-init.gradle` from these inputs
> Generate build-scan-init.gradle from the reference init-script

- agent/service-message-maven-extension/.mvn/wrapper/maven-wrapper.properties
- agent/service-message-maven-extension/mvnw
- agent/service-message-maven-extension/mvnw.cmd
Bumps Maven Wrapper from 3.9.6 to 3.9.9.
Release notes of Maven 3.9.9 can be found here:
https://maven.apache.org/docs/3.9.9/release-notes.html
> Bump Maven Wrapper from 3.9.6 to 3.9.9 in /agent/service-message-maven-extension

- README.md
- agent/build.gradle
- agent/service-message-maven-extension/.mvn/extensions.xml
- agent/service-message-maven-extension/pom.xml
- agent/service-message-maven-extension/src/main/java/nu/studer/teamcity/buildscan/agent/servicemessage/BuildScanServiceMessageListener.java
- agent/src/main/java/nu/studer/teamcity/buildscan/agent/BuildScanServiceMessageInjector.java
- agent/src/test/groovy/nu/studer/teamcity/buildscan/agent/maven/BaseExtensionApplicationTest.groovy
- src/main/resources/default-plugin-versions.properties
- src/test/groovy/nu/studer/teamcity/buildscan/connection/DevelocityConnectionProviderTest.groovy
Updated DV extension version everywhere:
- Update bundled version
- Update default version applied in tests
- Update version used by Maven build
- Update all doc references
Adds a static guard to prevent duplicate listener calls due to bug in 1.23.1
> Update develocity-maven-extension to v1.23.2
